### ISSUE TITLE
Add support for before & after steps for commands

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#1]
ex, 

```yaml
project: JUnit5
before: sh setup-seed-data.sh
after: sh delet-seed-data.sh
commands:
  - test: ./gradlew test
  - run: ./gradlew clean build
  - lint: ./gradlew spotlessApply
```
