### ISSUE TITLE
set dynamic values with 1build yaml configuration file

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#100]
## Description
Imagine you have to run specific command just toggling one value in it. For example, running your spring boot application with a different profile. The current 1build configuration might look like – 

```yaml
project: spring project
commands:
  - run: mvn spring-boot:run -Dspring-boot.run.profiles=local
  - run-dev: mvn spring-boot:run -Dspring-boot.run.profiles=dev
  - run-staging: mvn spring-boot:run -Dspring-boot.run.profiles=staging
  - run-uat: mvn spring-boot:run -Dspring-boot.run.profiles=uat
``` 

With this new feature, you can just write like configuration file like,

```yaml
project: spring project
commands:
  - run: mvn spring-boot:run -Dspring-boot.run.profiles={{profile:=local}}
``` 
Where `profile` is variable and the default value is `local`.

Now you can use command `1build run dev` to run the application using `dev` profile 

OR 

`1build run --profile staging` to run using staging profile.

## Acceptance Criteria
- Use of variables in `1build` configuration file.
- If a named variable is not present use the sequence of input at variable left to right

@landpro and @Ritabrata-TW 
WDYT about this feature?
