### ISSUE TITLE
Simplify configuration structure – remove description

### ISSUE THREAD

**Issue by landpro** [gopinath-langote/1build#19]
```yaml
project: JUnit5
commands:
  - test: source ./gradlew test
  - run: ./gradlew clean build
  - lint: ./gradlew spotlessApply
```
