### ISSUE TITLE
`before` and `after` life cycle hooks per each command

### ISSUE THREAD

**Issue by akhilbojedla** [gopinath-langote/1build#196]
## Description
Currently, we have `before` and `after` life cycle hooks that get executed before and after all the specified commands are executed. However, In some scenarios, it might be the case that we also need more granular life cycle hooks within the scope of a single command.

```
project: Sample Web App
before: export VARNAME="my value"
after: unset VARNAME
commands:
   - build: 
        before: echo "before"
        command: npm run build
        after: echo "after"
```

## Acceptance Criteria

- User should be able to define `before` and `after` for each individual command
- Should be able to disable global `before` and `after` for an individual command
