### ISSUE TITLE
Support for set/unset command definitions by 1build command

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#33]
Initial `1build.yaml`–

```yaml
project: JUnit5
commands:
  - run: ./gradlew clean build
  - lint: ./gradlew spotlessApply
```

---
After command `1build set test=./gradlew test`

The resulting file will be

```yaml
project: JUnit5
commands:
  - run: ./gradlew clean build
  - lint: ./gradlew spotlessApply
  - test: ./gradlew test
```

Similarly after command `1build unset lint`

The resulting file will be

```yaml
project: JUnit5
commands:
  - run: ./gradlew clean build
  - test: ./gradlew test
```
