### ISSUE TITLE
Create 1build configuration by `1build --init <project_name> 

### ISSUE THREAD

**Issue by gopinath-langote** [gopinath-langote/1build#84]
- Developer should be able to create a sample project configuration by 

```bash
1build --init "Sample Project"
```

or

```bash
1build --init sample
```

Will Result into:

Current directory having `1buil.yaml` with the following content
```yaml
project: <user_given_name>
commands:
  - build: echo 'Running build'
```

Note: `use 2 spaces indentation for commands `
